name: Firefox Create Release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm ci

      - name: Build Firefox extension
        run: npm run build:firefox

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Firefox Extension ${{ github.ref_name }}
          body: 'Automated release of Firefox extension.'
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload XPI to Release
        uses: softprops/action-gh-release@v2
        with:
          files: extension.xpi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

